version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Preserva node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # ← AGREGAR: Para Windows

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
